//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kragle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kragle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archives.
        /// </summary>
        internal static string ArchiveDirectory {
            get {
                return ResourceManager.GetString("ArchiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        internal static string CodeDirectory {
            get {
                return ResourceManager.GetString("CodeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commands.
        /// </summary>
        internal static string CommandsCsv {
            get {
                return ResourceManager.GetString("CommandsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000000.
        /// </summary>
        internal static string CommandsCsvLinesPerFile {
            get {
                return ResourceManager.GetString("CommandsCsvLinesPerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logs.
        /// </summary>
        internal static string LogDirectory {
            get {
                return ResourceManager.GetString("LogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to procedures.
        /// </summary>
        internal static string ProceduresCsv {
            get {
                return ResourceManager.GetString("ProceduresCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ProceduresCsvLinesPerFile {
            get {
                return ResourceManager.GetString("ProceduresCsvLinesPerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        internal static string ProjectDirectory {
            get {
                return ResourceManager.GetString("ProjectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remixes.
        /// </summary>
        internal static string ProjectRemixCsv {
            get {
                return ResourceManager.GetString("ProjectRemixCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ProjectRemixCsvLinesPerFile {
            get {
                return ResourceManager.GetString("ProjectRemixCsvLinesPerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        internal static string ProjectsCsv {
            get {
                return ResourceManager.GetString("ProjectsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000000.
        /// </summary>
        internal static string ProjectsCsvLinesPerFile {
            get {
                return ResourceManager.GetString("ProjectsCsvLinesPerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled..
        /// </summary>
        internal static string ResetConfirmCancel {
            get {
                return ResourceManager.GetString("ResetConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed all users, projects, and code..
        /// </summary>
        internal static string ResetConfirmSuccess {
            get {
                return ResourceManager.GetString("ResetConfirmSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all users, projects, and code? (y/n).
        /// </summary>
        internal static string ResetRequestConfirmation {
            get {
                return ResourceManager.GetString("ResetRequestConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scripts.
        /// </summary>
        internal static string ScriptsCsv {
            get {
                return ResourceManager.GetString("ScriptsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000000.
        /// </summary>
        internal static string ScriptsCsvLinesPerFile {
            get {
                return ResourceManager.GetString("ScriptsCsvLinesPerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        internal static string UserDirectory {
            get {
                return ResourceManager.GetString("UserDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        internal static string UsersCsv {
            get {
                return ResourceManager.GetString("UsersCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string UsersCsvLinesPerFile {
            get {
                return ResourceManager.GetString("UsersCsvLinesPerFile", resourceCulture);
            }
        }
    }
}
